### ISSUE TITLE
Multiple input data (2 variables)

### ISSUE THREAD

**Issue by surjithbs17** [tgjeon/TensorFlow-Tutorials-for-Time-Series#9]
When I tried your reference for giving multiple inputs (3 variables), and one output for prediction. I get an issue of lhs not matching rhs. Somewhere deep inside the abstraction. 

I modified the code in load_predictor.py.  for loading my csv file. I have attached the screen log in the attachments. 
[log.txt](https://github.com/tgjeon/TensorFlow-Tutorials-for-Time-Series/files/889110/log.txt)

[LSTM-Time-Series-Analysis-using-Tensorflow.zip](https://github.com/tgjeon/TensorFlow-Tutorials-for-Time-Series/files/889113/LSTM-Time-Series-Analysis-using-Tensorflow.zip)

I took @pusj latest updated code. I have attached the log below. Can someone help me with this?

**Comment by surjithbs17** [comment]
Looks like I just solved the bug. Clearing the resources folder(log) before running the code.

That solved the issue.

**Comment by RafaelFPinheiro** [comment]
@surjithbs17 can share the solution ?
